### ISSUE TITLE
Add git tags for the repo

### ISSUE THREAD

**Issue by Piicksarn** [icodeforlove/Console.js#10]
Hi @icodeforlove,
Would you mind to add the git tags for the repo? :smiley: 
After using the tags for the repo, it will be helpful for user to know the version and status of repository.
Furthermore, when Console.js release new versions, [cdnjs](https://github.com/cdnjs/cdnjs) could auto-update by the tags.

Thank you! :pray:

**Comment by Piicksarn** [comment]
✨ @icodeforlove ✨ 
I'd like to add tag@0.0.2 for the lib.
Which shown below are few latest log messages, and which one you think is better to be milestone.
`(aa9bcc8 or f99584b ?)`

```
aa9bcc8 Merge pull request #5 from acidghost/issue-4
3996c03 linted & built
085cc98 Function.prototype.bind not supported by iOS 5
f9c461c Merge pull request #3 from acidghost/pretty-print-objects
f99584b Release v0.0.2
5a0471e commit bumped version
```

**Comment by icodeforlove** [comment]
`aa9bcc8` is fine :)
