### ISSUE TITLE
Does not work for Edge or Firefox 60.

### ISSUE THREAD

**Issue by JSideris** [icodeforlove/Console.js#12]
My code:
```JavaScript
Console.attach();
Console.styles.attach();

Console.styles.register({
	impact: 'font-family: Impact',
	big: 'font-size:72px',

	red: 'color:#FAA',
	blue: 'color:#AAF',
	blackbg: 'background:#222',
});

console.log(" HELLO".big.impact.red.blackbg + "WORLD".big.impact.blue.blackbg);
```

Expected output (demonstrated in chrome): 
![image](https://user-images.githubusercontent.com/8083793/42412746-3b106616-81e0-11e8-932f-fe2f2fa08a4c.png)

Firefox (ignore the webgl warning - unrelated): 
![image](https://user-images.githubusercontent.com/8083793/42412752-4b947004-81e0-11e8-97e0-0d1efcd2af51.png)

Edge:

![image](https://user-images.githubusercontent.com/8083793/42412758-6ab616ea-81e0-11e8-8e56-9a916d9bf03b.png)

Please update!

**Comment by icodeforlove** [comment]
This will be fixed in #13
