### ISSUE TITLE
can I haz animations ?

### ISSUE THREAD

**Issue by koraysels** [icodeforlove/Console.js#7]
hi!
love the plugin!
I am trying to get css3 animations to work :p  do you know if that is possible ? I cant seem to do it..

**Comment by icodeforlove** [comment]
From what i understand this is impossible, the only time you see "animations" in the console is when someone logs very fast multiline messages and slowly changes the log message.

**Comment by icodeforlove** [comment]
Closing this because you cant add CSS other than inline styles to console.log messages.
