### ISSUE TITLE
this needs to be on NPM

### ISSUE THREAD

**Issue by summivox** [icodeforlove/Console.js#8]
unfortunately the name is not very descriptive... meanwhile `console.js` and `consolejs` are both taken and stand for drastically different things.

I suggest `console-modernize` (`console-polyfill` is squatted by paulmillr with a useless dummy).

**Comment by icodeforlove** [comment]
This was written a while ago, before it was common to have this kinda of level of cross compatibility.

If you would like to help make this possible we would need to do the following

- [ ] have some sort of fallback when its not loaded via browser
- [ ] move towards node modules format
- [ ] * bonus * switch to webpack

**Comment by icodeforlove** [comment]
This will be covered by #13
