### ISSUE TITLE
The library request in cdnjs

### ISSUE THREAD

**Issue by Piicksarn** [icodeforlove/Console.js#9]
Hi @icodeforlove
There's a library request in [cdnjs](https://github.com/cdnjs/cdnjs), and we desire to contain **Console.js**.
However, i must to make a check for the files that we need to added.

The files i would like to added are: 
 - console.js 
 - console.min.js

Is that complete for the user?

--

Thanks for your great work :sparkles:  

Piicksarn

**Comment by icodeforlove** [comment]
:), yeah thats all the would needed

thanks for adding it
